apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yuthikaVJ/End-to-End-Devops-Project-springboot-eks.git
    targetRevision: main
    path: helm/spring-boot-app
    
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: springboot

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    syncOptions:
      - CreateNamespace=true
